import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/app/components/header'
import Navbar from '@/app/components/navbar'
import { SessionProvider } from "next-auth/react"
import SessionProviderWrapper from './components/SessionProviderWrapper'
import WebSocketConnector from './components/webSocketConnector'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SessionProviderWrapper>
                    <WebSocketConnector />
                    <Header />
                    <div className="flex h-screen w-full overflow-hidden">
                        <Navbar />
                        <main className="flex-1 overflow-auto p-6">{children}</main>
                    </div>
                </SessionProviderWrapper>
            </body>
        </html>
    )
}
