# Generated by Django 5.2 on 2025-05-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readcourse',
            unique_together={('user_id', 'course_id')},
        ),
    ]
