# Generated by Django 5.2 on 2025-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
