# Generated by Django 5.2 on 2025-05-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0002_alter_readcourse_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='chapter_id',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='attempt_id',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='readcourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='readcourse',
            old_name='user_id',
            new_name='user',
        ),
    ]
