# Generated by Django 5.2 on 2025-05-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0002_course_description'),
        ('db_handler', '0003_rename_course_id_chapter_course_and_more'),
    ]

    operations = [
    ]
