# Generated by Django 5.2 on 2025-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0003_rename_course_id_chapter_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='attempt_ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='attempt_started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempt_started_at',
            field=models.DateTimeField(),
        ),
    ]
