# Generated by Django 5.2 on 2025-05-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0004_alter_quizanswer_attempt_ended_at_and_more'),
        ('db_handler', '0004_merge_20250510_1105'),
    ]

    operations = [
    ]
