# Generated by Django 5.2 on 2025-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_handler", "0004_alter_quizanswer_attempt_ended_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizanswer",
            name="attempt_ended_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="attempt_ended_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="attempt_started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
