# Generated by Django 5.2 on 2025-05-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0005_merge_20250517_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='free_text_answer',
        ),
    ]
