# Generated by Django 5.2 on 2025-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0006_remove_question_free_text_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='alt_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='alt_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='alt_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
