# Generated by Django 5.2 on 2025-05-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0005_remove_question_free_text_answer_and_more'),
        ('db_handler', '0008_alter_question_alt_1_alter_question_alt_2_and_more'),
    ]

    operations = [
    ]
