# Generated by Django 5.2 on 2025-05-21 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0009_merge_20250518_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
