# Generated by Django 5.2 on 2025-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0009_merge_20250518_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='free_text_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
