# Generated by Django 5.2 on 2025-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0010_alter_quizanswer_free_text_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='multiple_chooice_answer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
