# Generated by Django 5.2 on 2025-05-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0010_friendinvites'),
        ('db_handler', '0011_alter_quizanswer_multiple_chooice_answer'),
    ]

    operations = [
    ]
